version: "2.21.0"

services:

    bot:
        build: bot/

        command: ["pyton", "main.py"]

        depends_on:
            - database



    database:
        image: "mysql"

        ports:
            - "3306:3306"
